### ISSUE TITLE
images-api-pipeline #125 failed

### ISSUE THREAD

**Issue by piotrkosyoo** [piotrkosyoo/images-api#13]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 78 lines...]
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build684755044=/tmp/go-build -gno-record-gcc-switches"
[Pipeline] sh
+ go version
go version go1.10.6 linux/amd64
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build UI)
[Pipeline] script
[Pipeline] {
[Pipeline] dir
Running in /var/lib/jenkins/workspace/images-api-pipeline/client-api
[Pipeline] {
[Pipeline] sh
+ npm -v
/var/lib/jenkins/workspace/images-api-pipeline/client-api@tmp/durable-c4d9d878/script.sh: line 1: npm: command not found
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/125/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 41 lines...]
Cloning repository https://github.com/piotrkosyoo/images-api.git
 > git init /var/lib/jenkins/workspace/images-api-pipeline # timeout=10
Fetching upstream changes from https://github.com/piotrkosyoo/images-api.git
 > git --version # timeout=10
using GIT_SSH to set credentials github
 > git fetch --tags --progress https://github.com/piotrkosyoo/images-api.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/piotrkosyoo/images-api.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/piotrkosyoo/images-api.git # timeout=10
Fetching upstream changes from https://github.com/piotrkosyoo/images-api.git
using GIT_SSH to set credentials github
 > git fetch --tags --progress https://github.com/piotrkosyoo/images-api.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/develop^{commit} # timeout=10
Checking out Revision fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae (origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae # timeout=10
Commit message: "Update UI add modal"
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Prepare)
[Pipeline] sh
+ mkdir /var/lib/jenkins/go/src/images-api
mkdir: cannot create directory ‘/var/lib/jenkins/go/src/images-api’: File exists
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build UI)
Stage "Build UI" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

- [piotr] fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae - Update UI add modal



[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/126/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 83 lines...]
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build181288676=/tmp/go-build -gno-record-gcc-switches"
[Pipeline] sh
+ go version
go version go1.10.6 linux/amd64
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build UI)
[Pipeline] script
[Pipeline] {
[Pipeline] dir
Running in /var/lib/jenkins/workspace/images-api-pipeline/client-api
[Pipeline] {
[Pipeline] sh
+ npm -v
/var/lib/jenkins/workspace/images-api-pipeline/client-api@tmp/durable-88249368/script.sh: line 1: npm: command not found
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

- [piotr] fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae - Update UI add modal

No changes


[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/127/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 119 lines...]
[Pipeline] stage
[Pipeline] { (Build UI)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] dir
Running in /var/lib/jenkins/workspace/images-api-pipeline/client-api
[Pipeline] {
[Pipeline] sh
+ npm -v
6.5.0
[Pipeline] sh
+ node -v
v11.9.0
[Pipeline] sh
+ npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2019-02-02T18_11_58_973Z-debug.log
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

- [piotr] fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae - Update UI add modal

No changes
No changes


[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/128/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 171 lines...]
    at onCompiled (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/webpack/lib/Compiler.js:224:21)
    at hooks.afterCompile.callAsync.err (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/webpack/lib/Compilation.js:1295:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/webpack/lib/Compilation.js:1286:32)
Read more here: http://bit.ly/CRA-build-minify

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-api@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client-api@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2019-02-02T18_46_47_592Z-debug.log
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

- [piotr] fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae - Update UI add modal

No changes
No changes
- [piotr] b1005a78c97dd76dc82a8f70fe9c8216b85b1dc5 - Update UI add modal



[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/129/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 115 lines...]
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build UI)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] dir
Running in /var/lib/jenkins/workspace/images-api-pipeline/client-api
[Pipeline] {
[Pipeline] sh
+ npm -v
6.5.0
[Pipeline] sh
+ node -v
v11.9.0
[Pipeline] sh
+ yarn install
/var/lib/jenkins/workspace/images-api-pipeline/client-api@tmp/durable-1cd3622b/script.sh: line 1: yarn: command not found
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 52572549ca5f39410cc86e028d45dec26a232808 - Update UI add modal

- [piotr] fd9967ccfbaffa779c85f1f2e43ccca35d8f58ae - Update UI add modal

No changes
No changes
- [piotr] b1005a78c97dd76dc82a8f70fe9c8216b85b1dc5 - Update UI add modal

- [piotr] be08df45c0523b53506b0a9a745ec9c548827bc5 - Add lock file

- [piotr] 0361f3bce6b8c9374bedf95524fdebdf4cd0b811 - Change script

- [piotr] f10f2cdeeb7a3665a8a58e4a626e5026d77d1fb5 - Change script

- [piotr] 2bccbc4fef8f6c4a72c5f287f5fd97b2bf00694e - Fix error with plugin



[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/130/)

**Comment by piotrkosyoo** [comment]
Error build

Build 'images-api-pipeline' is failing!

Last 50 lines of build output:

```
[...truncated 138 lines...]
> styled-components@3.4.10 postinstall /var/lib/jenkins/workspace/images-api-pipeline/client-api/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1977 packages from 767 contributors and audited 35792 packages in 31.513s
found 0 vulnerabilities

[Pipeline] sh
+ npm run build

> client-api@0.1.0 build /var/lib/jenkins/workspace/images-api-pipeline/client-api
> node scripts/build.js

Creating an optimized production build...
sh: fork: Cannot allocate memory
wrapper script does not seem to be touching the log file in /var/lib/jenkins/workspace/images-api-pipeline/client-api@tmp/durable-73514032
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build backend)
Resuming build at Wed Feb 06 22:12:55 UTC 2019 after Jenkins restart
Waiting to resume part of images-api-pipeline #132: ???
Ready to run at Wed Feb 06 22:13:06 UTC 2019
Stage "Build backend" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Clean)
Stage "Clean" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (deploy)
Stage "deploy" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step

```

Changes since last successful build:
- [piotr] 1f89b09479044700c6e7608ae5ef60a4f3e8767c - Fix file-service



[View full output](http://ec2-63-33-63-206.eu-west-1.compute.amazonaws.com:8080/job/images-api-pipeline/132/)
